name: Classic-feature-branch-build

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v1

      #    - uses: BigWigsMods/packager@master
      #      name: Build Retail and upload to CurseForge
      #      with:
      #        args: -l -d
      #      - uses: BigWigsMods/packager@master
      #        name: Build Classic and upload to CurseForge
      #        with:
      #          args: -n help

      - uses: BigWigsMods/packager@master
        name: Build Classic
        with:
          args: -r ./zip -z -d -g classic

      - name: Name artifact with git hash
        run: echo 'ARTIFACT_NAME=${{ github.event.repository.name }}-'$(git -C ./zip show --no-patch --format="%H") >> $GITHUB_ENV

      - name: Store built zip
        uses: actions/upload-artifact@v2
        with:
          name : ${{ env.ARTIFACT_NAME }}
          path: ./zip/


    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./zip/
